---
contentdir: "content"
layoutdir: "layouts"
indexes:
  category: "categories"
publishdir: "public"
baseurl: "https://8574e5b7f5ebe4.github.io/blog/"
title: "Blog"
theme: "Lanyon"
canonifyurls: true
...
